### ISSUE TITLE
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached

### ISSUE THREAD

**Issue by emouawad** [rnwood/smtp4dev#1200]
```logs

smtp4dev version 3.2.0-ci20220905102
https://github.com/rnwood/smtp4dev
.NET Core runtime version: .NET 6.0.5

 > For help use argument --help

Install location: /
DataDir: /smtp4dev
A unhandled exception occurred.
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Rnwood.Smtp4dev.Program.<>c__DisplayClass8_0.<BuildWebHost>b__0(HostBuilderContext hostingContext, IConfigurationBuilder configBuilder) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Program.cs:line 164
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Rnwood.Smtp4dev.Program.BuildWebHost(String[] args, CommandLineOptions cmdLineOptions, MapOptions`1 commandLineOptions) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Program.cs:line 199
   at Rnwood.Smtp4dev.Program.StartApp(IEnumerable`1 args, Boolean isDesktopApp, Action`1 fixedOptions)
   at Rnwood.Smtp4dev.Program.Main(String[] args) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Program.cs:line 38

```

**Comment by emouawad** [comment]
This is apparently related to [stackoverflow](https://stackoverflow.com/questions/43469400/asp-net-core-the-configured-user-limit-128-on-the-number-of-inotify-instance) - Disabling the reloadOnChange should fix it.

Suggestion is:

```csharp

public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            config.AddJsonFile("appsettings.json",
                optional: true,
                reloadOnChange: false);
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
}

```

**Comment by emouawad** [comment]
Was able to fix it by adding:
```
ASPNETCORE__hostBuilder__reloadConfigOnChange: false
```

For context replicable on ubuntu ARM64 - maybe it should be added to the documentation if somebody else is facing same issue.
