### ISSUE TITLE
Exception when opening any attachment or viewing part content if message has some parts with a "Content-ID" and others without

### ISSUE THREAD

**Issue by sicknote** [rnwood/smtp4dev#138]
smtp4dev version 3.1.0-ci0552 within docker

I cannot seem to get any attachments to open from smtp4dev. 

The emails were sent using .Net SmtpClient, and do work fine when going to an actual mail client, but always fail in the smtp4dev browser. Same seems to happen in the non docker version.

`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Rnwood.Smtp4dev.ApiModel.Message.GetPartContent(Message result, String cid) in /app/Rnwood.Smtp4dev/ApiModel/Message.cs:line 122
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
`

**Comment by rnwood** [comment]
Thanks for the report. To make reproducing this easy, can you share 
either an example .eml file or some example code to send a message which 
fails in this way?

Thanks
Rob

------ Original Message ------

**Comment by sicknote** [comment]
[sample.zip](https://github.com/rnwood/smtp4dev/files/3284969/sample.zip)

The issue appears to be due to there being inline images attached using a cid:GUID, and the main attachment, which then has the object reference exception.

I'm creating a multi-part email, with a simple HTML part using one of the attached images in the display.

**Comment by rnwood** [comment]
Fixed in latest build.
