### ISSUE TITLE
Malformed MIME message content causes an uncaught exception

### ISSUE THREAD

**Issue by tkorc** [rnwood/smtp4dev#25]
When testing the communication using telnet app will raise an exception when clicking on item which has been sent using telnet (see how to sent it using telnet - https://technet.microsoft.com/en-us/library/aa995718(v=exchg.65).aspx?f=255&MSPPError=-2147217396)

Tested on current master branch (3.0) using Telnet on latest stable Windows 10 machine.

I'll try to fix it when I have a time within next two weeks and will do the PR eventually.

**Comment by rnwood** [comment]
Thanks for your report.

 This seems to occur because the example does not include any headers and is therefore a malformed MIME message:
```
System.FormatException
  HResult=0x80131537
  Message=Failed to parse message headers.
  Source=MimeKit
  StackTrace:
   at MimeKit.MimeParser.ParseMessage(Byte* inbuf, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(ParserOptions options, Stream stream, Boolean persistent, CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(Stream stream, Boolean persistent, CancellationToken cancellationToken)
   at Rnwood.Smtp4dev.Server.MessageConverter.Convert(Stream messageData) in C:\src\smtp4dev\Rnwood.Smtp4dev\Server\MessageConverter.cs:line 15
```
We need to figure out how to handle MIME parsing failure including displaying something sensible in the UI to show that the message is malformed.
