### ISSUE TITLE
smtp4dev doesn't specify SMTP Host.

### ISSUE THREAD

**Issue by Alek097** [rnwood/smtp4dev#454]
I've installed v3.1.1-ci2020083104, after that, I've set the tls mode as StartTls and run smtp4dev. Also, I've installed from logs of smtp4dev.
![image](https://user-images.githubusercontent.com/16559175/92416499-7f204180-f166-11ea-930e-71493aafbed9.png)
When I try to send an email message I see:

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The SMTP host was not specified.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at FluentEmail.Smtp.SmtpSender.Send(IFluentEmail email, Nullable`1 token)
   at FluentEmail.Core.Email.Send(Nullable`1 token)
   at Izba.Business.EmailService.SendEmail(IFluentEmail email) in D:\izba\Izba.Business\EmailService.cs:line 49
   at Izba.Business.EmailService.SendEmail(String to, String subject, EmailTemplate template) in D:\izba\Izba.Business\EmailService.cs:line 30
   at Izba.Business.IdentityService.SendRegistrationTokens(String email, String phoneNumber, IEmailService emailService, ISmsService smsService, IRegistrationTokenRepository tokenRepository) in D:\izba\Izba.Business\IdentityService.cs:line 65
   at Izba.Web.Controllers.Api.AuthController.SendRegistrationTokens(IEmailService emailService, ISmsService smsService, IRegistrationTokenRepository tokenRepository, String email, String phoneNumber) in D:\izba\Izba.Web\Controllers\Api\AuthController.cs:line 29
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: The SMTP host was not specified.

```

![image](https://user-images.githubusercontent.com/16559175/92416568-c9a1be00-f166-11ea-9ddd-710ce8b19444.png)

**Comment by rnwood** [comment]
Can you show how you are configuring the host and port for `SmtpClient` to connect to? Is this a .NET Framework or .NET Core application?

**Comment by rnwood** [comment]
IMO this is a client config issue, so closing for now.
