### ISSUE TITLE
Error on first startup - SQLite Error 1: 'table "Messages" already exists

### ISSUE THREAD

**Issue by michele-grifa** [rnwood/smtp4dev#488]
I have the following error when i try to start a docker container configured in my docker.compose.yml file under windows environment.
The docker-compose service is configured as follow

```yaml
smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - '5000:80'
      - '25:25'
    volumes:
      - smtp4dev-data:/smtp4dev
```

```
smtp4dev version 3.1.2-ci20200925100
https://github.com/rnwood/smtp4dev

.NET Core runtime version: 3.1.2


 > For help use argument --help

Using Sqlite database at /smtp4dev/database.db
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "Messages" (
          "Id" TEXT NOT NULL CONSTRAINT "PK_Messages" PRIMARY KEY,
          "From" TEXT NULL,
          "To" TEXT NULL,
          "ReceivedDate" TEXT NOT NULL,
          "Subject" TEXT NULL,
          "Data" BLOB NULL,
          "MimeParseError" TEXT NULL
      );
Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Messages" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Rnwood.Smtp4dev.Startup.<>c__DisplayClass5_0.<Configure>b__0(IApplicationBuilder subdir) in /app/Rnwood.Smtp4dev/Startup.cs:line 133
   at Rnwood.Smtp4dev.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory log) in /app/Rnwood.Smtp4dev/Startup.cs:line 152
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Messages" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Rnwood.Smtp4dev.Startup.<>c__DisplayClass5_0.<Configure>b__0(IApplicationBuilder subdir) in /app/Rnwood.Smtp4dev/Startup.cs:line 133
   at Rnwood.Smtp4dev.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory log) in /app/Rnwood.Smtp4dev/Startup.cs:line 152
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Messages" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Rnwood.Smtp4dev.Startup.<>c__DisplayClass5_0.<Configure>b__0(IApplicationBuilder subdir) in /app/Rnwood.Smtp4dev/Startup.cs:line 133
   at Rnwood.Smtp4dev.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory log) in /app/Rnwood.Smtp4dev/Startup.cs:line 152
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Rnwood.Smtp4dev.Program.Main(String[] args) in /app/Rnwood.Smtp4dev/Program.cs:line 44
```

**Comment by rnwood** [comment]
Thanks for reporting.

If you know how, can you please can you look at the `database.db` in a SQLite browser and tell me what's in the table `__EFMigrationsHistory`. If you don't know how and you're happy to share the messages etc in the DB with me privately then please send to rob@rnwood.co.uk.

Once you've done this, you can try rename the `database.db` and try start up again. Hopefully this will work - sorry don't understand what's happening here yet so cannot guarantee.

**Comment by michele-grifa** [comment]
How can i look at the `database.db` if the container is not starting? I don't have a mapped local copy.

**Comment by rnwood** [comment]
@michele-grifa 

I've fixed this issue in latest version pre-release version (>=3.1.2-ci20200925101 which will appear shortly). For now you can use label `3.1.1.1` if you are not interested in pre-release versions. I've created a ticket to switch the `latest` label over to point at the stabler releases as that makes sense for most people. I will also update the README etc to make it clear how to get pre-release vs release.

You will need to delete the file `/smtp4dev/database.db` within the container (or the whole anon volume for the container as per below) and then pull down the latest version or switch to above label. The simplest way to do this is to edit the label in your docker compose file and then
```
docker-compose pull
docker-compose up -d -V --force-recreate smtp4dev
```

I will keep this ticket open as I'd also like to modify the E2E tests so that they pick up DB creation issues like this regression.

**Comment by michele-grifa** [comment]
After updating to 3.1.1.1 and following the commands you indicated, the problem is solved
