### ISSUE TITLE
[BUG] Cannot find file "/appsettings.json" when launching as a service - Linux v3.0.248

### ISSUE THREAD

**Issue by alexpilon666** [rnwood/smtp4dev#50]
Hello!

Having a issue running v3.0.248 as service on Linux. 
I'm using the ZIP file containing all the necessary runtimes, and it was extracted all at one location, being `/etc/smtp4dev`. 
If I run the command manually in the terminal, `/etc/smtp4dev/Rnwood.Smtp4dev --server.urls "http://0.0.0.0:5001/"`, everything runs fine. 
When I use the same command in a `systemd` service, I get the following error: 

```
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]: Application startup exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/appsettings.json'.
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Rnwood.Smtp4dev.Startup..ctor(IHostingEnvironment env) in C:\projects\smtp4dev\Rnwood.Smtp4dev\Startup.cs:line 36
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]: --- End of stack trace from previous location where exception was thrown ---
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider,
Type serviceType)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]: Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/appsettings.json'.
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Rnwood.Smtp4dev.Startup..ctor(IHostingEnvironment env) in C:\projects\smtp4dev\Rnwood.Smtp4dev\Startup.cs:line 36
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]: --- End of stack trace from previous location where exception was thrown ---
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider,
Type serviceType)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
Aug 24 18:32:41 sidlee-mailhog Rnwood.Smtp4dev[26615]:    at Rnwood.Smtp4dev.Program.Main(String[] args) in C:\projects\smtp4dev\Rnwood.Smtp4dev\Program.cs:line 17
Aug 24 18:32:41 sidlee-mailhog systemd[1]: smtp4dev.service: Main process exited, code=dumped, status=6/ABRT
Aug 24 18:32:41 sidlee-mailhog systemd[1]: smtp4dev.service: Unit entered failed state.
Aug 24 18:32:41 sidlee-mailhog systemd[1]: smtp4dev.service: Failed with result 'core-dump'.
```

Here's my service configuration: 
```
[Unit]
Description=SMTP4DEV Service

[Service]
ExecStart=/etc/smtp4dev/Rnwood.Smtp4dev --server.urls "http://0.0.0.0:5001"

[Install]
WantedBy=multi-user.target
```

**Comment by rnwood** [comment]
Thanks for your bug report. I can reproduce this when running in systemd and I can see it's to do with how we set ContentRoot and BasePath from the current working directory. By default for systemd units the CWD is / and the files smtp4dev needs to run are not there.

You can set ``WorkingDirectory=/etc/smtp4dev`` in your systemd unit to make this work for now. I've tested this and it work ok.

To correct this properly we need to set contentroot/basepath correctly when running based on the location of the executable or main module. There's some handling already for this when running as a Windows Service with ``--service`` args.
