### ISSUE TITLE
Error while writing mail to DB

### ISSUE THREAD

**Issue by AFract** [rnwood/smtp4dev#615]
I have the following SQLite error with the last version when a mail is received :

> Message received. Client address 127.0.0.1. From xx To xx.
> Processing received message
> fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
>       Failed executing DbCommand (4ms) [Parameters=[@p0='?', @p1='?', @p2='?' (Size = 238353), @p3='?' (Size = 20), @p4='?', @p5='?', @p6='?', @p7='?', @p8='?', @p9='?' (Size = 92), @p10='?' (Size = 20)], CommandType='Text', CommandTimeout='30']
>       INSERT INTO "Messages" ("Id", "AttachmentCount", "Data", "From", "IsUnread", "MimeParseError", "ReceivedDate", "RelayError", "SessionId", "Subject", "To")
>       VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10);
> fail: Microsoft.EntityFrameworkCore.Update[10000]
>       An exception occurred in the database while saving changes for context type 'Rnwood.Smtp4dev.DbModel.Smtp4devDbContext'.
>       Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
>        ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): **SQLite Error 19: 'NOT NULL constraint failed: Messages.ImapUid'.**
>          at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>          at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
>          at System.Data.Common.DbCommand.ExecuteReader()
>          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
>          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>          --- End of inner exception stack trace ---
>          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
>          at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
>          at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
>          at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
>  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: Messages.ImapUid'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.ExecuteReader()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
>  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: Messages.ImapUid'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.ExecuteReader()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
>    at Rnwood.Smtp4dev.Server.Smtp4devServer.<>c__DisplayClass14_0.<OnMessageReceived>b__0() in /home/vsts/work/1/s/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 308
>    at Rnwood.Smtp4dev.Server.Smtp4devServer.<>c__DisplayClass11_0.<QueueTask>b__0() in /home/vsts/work/1/s/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 234
> Session completed. Client address 127.0.0.1. Number of messages 1.

Thank you

**Comment by rnwood** [comment]
It looks like you might be using an older smtp4dev version (< 3.1.2-ci20200925100) with a DB file which has been already upgraded by a later version (>= 3.1.2-ci20200925100). The ImapUid field was introduced in a recent version but your stack trace doesn't show it being set, which implies this combination.

You can double check what version is running here by looking at the console output on startup.

If I'm right:
- You can upgrade to a version >= 3.1.2-ci20200925100 and this error should go away. You won't lose the messages etc that are already in the DB.
or
- If you want to use the version you've already got running and you're happy to start afresh, you can simply stop smtp4dev and delete the .db file (path printed during startup) before starting again. You'll then get a new DB file with the schema correctly matching the binary you are using.

Please can you confirm if my guess is right here. If correct I'll consider implementing a 'DB version mismatch' error so that people can't accidentally get into this situation.

------ Original Message ------

**Comment by AFract** [comment]
Thank you !
I think you're right about the root cause.
Here's how it occured :
- I've downloaded the github version. 
Manually launching the EXE was ok and it received the emails the but I was unable to have it working in IIS.
- So I have used instead "dotnet tool install -g Rnwood.Smtp4dev". I guess this command line have installed an older version, and it has used the databased already generated in Roaming folder.
Regards,
Richard

**Comment by rnwood** [comment]
Keeping this ticket open to implement the DB version check on startup. If version is greater than expected then startup will fail with an appropriate error.
