### ISSUE TITLE
Relay between two instances of smtp4dev

### ISSUE THREAD

**Issue by thecliguy** [rnwood/smtp4dev#871]
Is it possible to run two instances of smtp4dev on the same machine, where the first instance is configured to relay to the second instance?

If this is possible, please can you provide an example of the configuration that would be required for the two instances? 

I've attempted to get this working but not succeeded so far.

**Comment by thecliguy** [comment]
@jafin Wouldn't the first instance need to include the following parameters to instruct it to use the second instance as a relay?

```
--relaysmtpserver=VALUE
                       Sets the name of the SMTP server that will be used
                         to relay messages or "" if messages relay should
                         not be allowed

--relayautomaticallyemails=VALUE
                       A comma separated list of recipient addresses for
                         which messages will be relayed automatically. An
                         empty list means that no messages are relayed
```

So for example, the commands for each instance would be something like this:

```
rnwood.smtp4dev --urls=http://*:5005 --smtpport=2525 --imapport=2445 --db=.\smtp2525\database.db --relaytlsmode=none --relayautomaticallyemails=test@example.com --relaysmtpport=2526
rnwood.smtp4dev --urls=http://*:5006 --smtpport=2526 --imapport=2446 --db=.\smtp2526\database.db --relaytlsmode=none
```

Even if I'm right about this, I still can't get it to work though...

**Comment by jafin** [comment]
@thecliguy I was now able to get this going, with a patched version , #877 .
I think the issue I was having was shared config in the APPDATA folder.  By allowing a custom basePath this fixes issue I saw.

```
rnwood.smtp4dev --basePath=c:\temp\smtp2 --urls=http://*:5006 --smtpport=2526 --imapport=2446 --relaytlsmode=none 
rnwood.smtp4dev --basePath=c:\temp\smtp1 --urls=http://*:5005 --smtpport=2525 --imapport=2445 --relaytlsmode=none --relaysmtpserver=localhost --relaysmtpport=2526 --relayautomaticallyemails=test@mailinator.com
```

![image](https://user-images.githubusercontent.com/127927/132077808-cf717b29-0dee-4b5d-bd0f-2cd6928acc6e.png)

**Comment by jafin** [comment]
@thecliguy ,  a preview build is available that includes the change for the baseappdirpath.  With these changes I can run 2 instances.  Would you be able to see if it solves your issue?

**Comment by thecliguy** [comment]
> 
> 
> @thecliguy , a preview build is available that includes the change for the baseappdirpath. With these changes I can run 2 instances. Would you be able to see if it solves your issue? (https://github.com/rnwood/smtp4dev/releases/tag/3.1.3-ci20210907116)

Hi @jafin - I'm a bit confused, there doesn't seem to be a parameter called `baseappdirpath`.

Am I supposed to be using `baseappdatapath` or `basepath`?

**Comment by jafin** [comment]
Apologies it is `--baseappdatapath` .  Running the cmd with -h should emit all the command line options available. 
If you are able to configure 2 locations with separate configs, similar to discussion above, then you should be able to have 2 instances running on the same PC.

**Comment by thecliguy** [comment]
@jafin It's not working quite right... 

Here's the commands I used to start the two instances of smtp4dev:
```
"C:\Bitbucket\Rnwood.Smtp4dev-win-x64-3.1.3-ci20210907116\Rnwood.Smtp4dev.exe" --baseappdatapath=c:\temp\smtp1 --urls=http://*:5005 --smtpport=2525 --imapport=2445 --relaytlsmode=none --relaysmtpserver=localhost --relaysmtpport=2526 --relayautomaticallyemails=test@example.com
"C:\Bitbucket\Rnwood.Smtp4dev-win-x64-3.1.3-ci20210907116\Rnwood.Smtp4dev.exe" --baseappdatapath=c:\temp\smtp2 --urls=http://*:5006 --smtpport=2526 --imapport=2446 --relaytlsmode=none
```

I then sent an email via 127.0.0.1 on port 2525 using PowerShell's `Send-MailMessage` cmdlet:
```powershell
Send-MailMessage -To "test@example.com" -From "NoReply@example.com" -Subject "Test Subject" -Body "Test Body" -SmtpServer 127.0.0.1 -Port 2525
```

It seems as though the `--relaysmtpport=2526` parameter is being ignored because if the error message that's being returned can be trusted it suggests that relaying is using port 25:

```
No connection could be made because the target machine actively refused it. 127.0.0.1:25
```

Here's the full error:
```
Session started. Client address 127.0.0.1.
Message received. Client address 127.0.0.1. From NoReply@example.com. To test@example.com.
Processing received message
Relaying message to test@example.com
Can not relay message to test@example.com: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:25
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Rnwood.Smtp4dev.Startup.<>c.<ConfigureServices>b__4_1(RelayOptions relayOptions) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Startup.cs:line 76
   at Rnwood.Smtp4dev.Server.Smtp4devServer.TryRelayMessage(Message message, MailboxAddress[] overrideRecipients) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 326
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 127.0.0.1:25
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Rnwood.Smtp4dev.Startup.<>c.<ConfigureServices>b__4_1(RelayOptions relayOptions) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Startup.cs:line 76
   at Rnwood.Smtp4dev.Server.Smtp4devServer.TryRelayMessage(Message message, MailboxAddress[] overrideRecipients) in /home/vsts/work/1/s/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 326
Processing received message DONE
Session completed. Client address 127.0.0.1. Number of messages 1.
```

**Comment by jafin** [comment]
@thecliguy  - It's a bug, the RelaySmtpPort was not being set correctly.  I've put in a PR to resolve.
