### ISSUE TITLE
Unable to run v3.1.2 in Windows Docker container

### ISSUE THREAD

**Issue by qoobic** [rnwood/smtp4dev#999]
Issue 302 (https://github.com/rnwood/smtp4dev/issues/302) appears to be present when running v3.1.2 in Windows on Docker. Output below:

```
PS C:\Users\Administrator> docker run rnwood/smtp4dev:windows-amd64-3.1.2
smtp4dev version 3.1.2-ci20210315103
https://github.com/rnwood/smtp4dev

.NET Core runtime version: 3.1.2


 > For help use argument --help

docker : Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\smtp4dev' is denied.
At line:1 char:1
+ docker run rnwood/smtp4dev:windows-amd64-3.1.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...dev' is denied.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Environment.set_CurrentDirectoryCore(String value)
   at System.Environment.set_CurrentDirectory(String value)
   at System.IO.Directory.SetCurrentDirectory(String path)
   at Rnwood.Smtp4dev.Program.BuildWebHost(String[] args) in C:\app\Rnwood.Smtp4dev\Program.cs:line 96
   at Rnwood.Smtp4dev.Program.Main(String[] args) in C:\app\Rnwood.Smtp4dev\Program.cs:line 34
```

I've included the output from v3.1.0-ci2020031904 below for comparison:

```
PS C:\Users\Administrator> docker run rnwood/smtp4dev:windows-amd64-3.1.0-ci2020031904
smtp4dev version 3.1.0-ci2020031904
https://github.com/rnwood/smtp4dev

.NET Core runtime version: 3.1.2

Using Sqlite database at C:\app\database.db
SMTP Server is listening on port 25. Keeping last 100 messages and 100 sessions.
Hosting environment: Production
Content root path: C:\app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
Message/session consuming thread running.
```

_Originally posted by @qoobic in https://github.com/rnwood/smtp4dev/issues/302#issuecomment-1000235452_

**Comment by qoobic** [comment]
Same is true on `rnwood/smtp4dev:windows-amd64-latest`, I just checked.

**Comment by rnwood** [comment]
I'm unable to reproduce this even with the exact tag mentioned here. @qoobic can you please confirm you still have the issue. Can you confirm the version of Windows and Docker that you are using.

If you still get the problem, please can you try the latest stable (label 'latest') and prerelease versions (label 'prerelease').
